"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Lock, Mail, X } from "lucide-react";
import { MIN_PASSWORD_LENGTH } from "@/lib/auth";
import type { AuthApiResponse, SignupRequest } from "@/types";
export function EmailSignupForm({ onClose }: { readonly onClose: () => void }) {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (password !== confirmPassword) return setError("비밀번호가 일치하지 않습니다."); if (password.length < MIN_PASSWORD_LENGTH) return setError(`비밀번호는 ${MIN_PASSWORD_LENGTH}자 이상이어야 합니다.`); setLoading(true); setError(""); try { const response = await fetch("/api/auth/signup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password } satisfies SignupRequest) }); const data = (await response.json()) as AuthApiResponse; if (!response.ok || !data.success) return setError(data.success ? "회원가입에 실패했습니다." : data.error); router.push(`/verify-email?email=${encodeURIComponent(email.trim())}`); } catch (caught) { if (!(caught instanceof TypeError)) throw caught; setError("서버와 연결할 수 없습니다."); } finally { setLoading(false); } }
  return <div><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-bold text-white">이메일 회원가입</h2><button type="button" onClick={onClose} aria-label="닫기"><X className="h-5 w-5" /></button></div><p className="mb-5 text-sm text-zinc-400">인증 후 이름, 핸들, 선택 설정과 약관 동의를 완료합니다.</p><form onSubmit={submit} className="space-y-4"><label className="block text-xs text-zinc-400">이메일<div className="relative mt-1"><Mail className="absolute left-4 top-4 h-4 w-4" /><input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} className="h-12 w-full rounded-lg border border-white/10 bg-black/50 pl-11 pr-4 text-white" /></div></label><label className="block text-xs text-zinc-400">비밀번호<div className="relative mt-1"><Lock className="absolute left-4 top-4 h-4 w-4" /><input type="password" required value={password} onChange={(event) => setPassword(event.target.value)} className="h-12 w-full rounded-lg border border-white/10 bg-black/50 pl-11 pr-4 text-white" /></div></label><label className="block text-xs text-zinc-400">비밀번호 확인<input type="password" required value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} className="mt-1 h-12 w-full rounded-lg border border-white/10 bg-black/50 px-4 text-white" /></label>{error && <p role="alert" className="text-sm text-red-400">{error}</p>}<button disabled={loading} className="h-12 w-full rounded-lg bg-brand-neon font-bold text-black disabled:opacity-60">{loading ? "처리 중..." : "다음 — 이메일 인증"}</button></form></div>;
}
