-- Supabase Data API(PostgREST)는 public schema table을 공개 key로 노출하므로, RLS가 꺼져 있으면 누구나 CRUD할 수 있다.
-- 앱은 Data API를 쓰지 않는다(Prisma = BYPASSRLS인 postgres role 또는 table owner, Storage = 서버 전용 service_role).
-- 그래서 policy 없이 RLS만 켜서 anon·authenticated role의 Data API 접근을 막는다(fail-closed).
-- service_role은 BYPASSRLS라 계속 접근 가능하므로 그 key는 서버 밖으로 내보내지 않는다.
-- NOTE: 새 table을 만들면 그 table의 RLS를 켜는 SQL도 migration에 넣는다(prisma/rls-coverage.test.ts가 강제).
ALTER TABLE "AdminStepUpProof" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Answer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BenefitAdminAudit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CartItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CouponCampaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CouponIssuanceBatch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Follow" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InventoryAdjustment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LegalDocumentVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OOTDComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OOTDLike" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OOTDPost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OOTDPostProduct" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Order" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PointLedgerEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PointPolicy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductVariant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Question" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecentTryOn" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Review" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserConsent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserCouponGrant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationCode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WishlistItem" ENABLE ROW LEVEL SECURITY;

-- Prisma가 관리하는 이력 table도 public에 있어 같이 막는다. shadow DB처럼 아직 없는 곳에서도 실패하지 않게 IF EXISTS.
ALTER TABLE IF EXISTS "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
