"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { LegalModal } from "@/components/legal/LegalModal";
import { ProfilePhotoField } from "@/components/onboarding/ProfilePhotoField";
import { validateHandle } from "@/lib/handle";
import type { LegalDocumentKey } from "@/lib/legal-documents";
import { LEGAL_VERSION, parseSafeReturnTo } from "@/lib/onboarding";
import { PREFERRED_SIZES } from "@/lib/user-settings";

type ProfileData = { readonly name: string; readonly avatar: string | null; readonly handle: string | null; readonly onboardingCompletedAt: string | null; readonly settings: { readonly preferredSize: string | null; readonly aiCoordinatorEnabled: boolean; readonly heightCm: number | null; readonly weightKg: number | null } };
type ConsentProps = { readonly checked: boolean; readonly onChange: (value: boolean) => void; readonly label: string; readonly documentKey: LegalDocumentKey; readonly onOpen: (key: LegalDocumentKey, trigger: HTMLElement) => void; readonly required?: boolean };

export function ProfileOnboardingForm({ returnTo }: { readonly returnTo: string }) {
  const router = useRouter();
  const [loaded, setLoaded] = useState(false); const [name, setName] = useState(""); const [avatar, setAvatar] = useState<string | null>(null); const [handle, setHandle] = useState(""); const [handleFeedback, setHandleFeedback] = useState(""); const [preferredSize, setPreferredSize] = useState(""); const [heightCm, setHeightCm] = useState(""); const [weightKg, setWeightKg] = useState(""); const [aiEnabled, setAiEnabled] = useState(true); const [terms, setTerms] = useState(false); const [privacy, setPrivacy] = useState(false); const [marketing, setMarketing] = useState(false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [legalKey, setLegalKey] = useState<LegalDocumentKey | null>(null); const [legalTrigger, setLegalTrigger] = useState<HTMLElement | null>(null);
  useEffect(() => { void fetch("/api/users/me/onboarding").then(async (response) => { if (response.status === 401) return router.replace(`/login?callbackUrl=${encodeURIComponent(`/onboarding/profile?returnTo=${returnTo}`)}`); const result = (await response.json()) as { success: boolean; data?: ProfileData; error?: string }; if (!result.success || !result.data) return setError(result.error ?? "프로필을 불러오지 못했습니다."); if (result.data.onboardingCompletedAt) return router.replace(parseSafeReturnTo(returnTo)); setName(result.data.name); setAvatar(result.data.avatar); setHandle(result.data.handle ?? ""); setPreferredSize(result.data.settings.preferredSize ?? ""); setHeightCm(result.data.settings.heightCm?.toString() ?? ""); setWeightKg(result.data.settings.weightKg?.toString() ?? ""); setAiEnabled(result.data.settings.aiCoordinatorEnabled); setLoaded(true); }).catch((caught: unknown) => { if (caught instanceof SyntaxError) setError("프로필을 불러오지 못했습니다. 서버 응답을 확인해 주세요."); else if (caught instanceof TypeError) setError("서버와 연결할 수 없습니다."); else throw caught; }); }, [returnTo, router]);
  async function submit(event: React.FormEvent) { event.preventDefault(); const checked = validateHandle(handle); if (!checked.ok) return setHandleFeedback(checked.error); setSaving(true); setError(""); try { const response = await fetch("/api/users/me/onboarding", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, handle, preferredSize: preferredSize || null, heightCm: heightCm === "" ? null : Number(heightCm), weightKg: weightKg === "" ? null : Number(weightKg), aiCoordinatorEnabled: aiEnabled, termsVersion: LEGAL_VERSION, privacyVersion: LEGAL_VERSION, termsAccepted: terms, privacyAccepted: privacy, marketingAccepted: marketing }) }); const result = (await response.json()) as { success: boolean; error?: string }; if (!response.ok || !result.success) return setError(result.error ?? "저장하지 못했습니다."); router.replace(parseSafeReturnTo(returnTo)); router.refresh(); } catch (caught) { if (caught instanceof SyntaxError) setError("저장 결과를 확인할 수 없습니다. 다시 시도해 주세요."); else if (caught instanceof TypeError) setError("서버와 연결할 수 없습니다."); else throw caught; } finally { setSaving(false); } }
  async function checkHandle() { const checked = validateHandle(handle); if (!checked.ok) return setHandleFeedback(checked.error); try { const response = await fetch(`/api/auth/handle/check?handle=${encodeURIComponent(handle)}`); const result = (await response.json()) as { readonly available: boolean }; setHandleFeedback(result.available ? "사용 가능한 핸들입니다." : "이미 사용 중인 핸들입니다."); } catch (caught) { if (!(caught instanceof TypeError)) throw caught; setHandleFeedback("핸들 중복 확인에 실패했습니다."); } }
  function openLegal(key: LegalDocumentKey, trigger: HTMLElement) { setLegalTrigger(trigger); setLegalKey(key); }
  if (!loaded && !error) return <p className="text-center text-zinc-400">프로필을 불러오는 중...</p>;
  return <form onSubmit={submit} className="space-y-6">
    <ProfilePhotoField avatar={avatar} onAvatarChange={setAvatar} />
    <section><p className="text-xs font-semibold uppercase tracking-widest text-brand-neon">필수 프로필</p><div className="mt-3 grid gap-4 sm:grid-cols-2"><label className="text-sm text-zinc-300">표시 이름<input value={name} onChange={(event) => setName(event.target.value)} required minLength={2} maxLength={50} className="mt-1 h-12 w-full rounded-xl border border-white/10 bg-black px-4 text-white" /></label><label className="text-sm text-zinc-300">핸들<div className="mt-1 flex h-12 items-center rounded-xl border border-white/10 bg-black"><span aria-hidden="true" className="pl-4 text-zinc-500">@</span><input aria-label="핸들" value={handle} onChange={(event) => { setHandle(event.target.value); setHandleFeedback(""); }} onBlur={() => void checkHandle()} required pattern="[a-z0-9_]{3,20}" className="h-full min-w-0 flex-1 bg-transparent px-1 pr-4 text-white outline-none" /></div><span className="mt-1 block text-xs text-zinc-500">영소문자·숫자·밑줄만 3~20자</span>{handleFeedback && <span role="status" className="mt-1 block text-xs text-zinc-300">{handleFeedback}</span>}</label></div></section>
    <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="text-xs font-semibold uppercase tracking-widest text-zinc-400">선택 설정</p><label className="mt-3 block text-sm text-zinc-300">선호 사이즈<select value={preferredSize} onChange={(event) => setPreferredSize(event.target.value)} className="mt-1 h-12 w-full rounded-xl border border-white/10 bg-black px-4"><option value="">나중에 설정</option>{PREFERRED_SIZES.map((size) => <option key={size}>{size}</option>)}</select></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm text-zinc-300">키 (cm)<input type="number" min="100" max="250" step="0.1" value={heightCm} onChange={(event) => setHeightCm(event.target.value)} className="mt-1 h-12 w-full rounded-xl border border-white/10 bg-black px-4" /></label><label className="text-sm text-zinc-300">몸무게 (kg)<input type="number" min="25" max="300" step="0.1" value={weightKg} onChange={(event) => setWeightKg(event.target.value)} className="mt-1 h-12 w-full rounded-xl border border-white/10 bg-black px-4" /></label></div><p className="mt-2 text-xs text-zinc-500">AI 스타일·핏 추천에만 사용하며 입력하지 않아도 가입할 수 있습니다.</p><label className="mt-4 flex gap-3 text-sm text-zinc-300"><input type="checkbox" checked={aiEnabled} onChange={(event) => setAiEnabled(event.target.checked)} />AI Coordinator 추천 표시</label></section>
    <section className="space-y-3"><p className="text-xs font-semibold uppercase tracking-widest text-brand-neon">약관 동의 · {LEGAL_VERSION}</p><Consent checked={terms} onChange={setTerms} required label="이용약관 동의 (필수)" documentKey="terms" onOpen={openLegal} /><Consent checked={privacy} onChange={setPrivacy} required label="개인정보 처리방침 동의 (필수)" documentKey="privacy" onOpen={openLegal} /><Consent checked={marketing} onChange={setMarketing} label="마케팅 이메일 수신 (선택)" documentKey="marketing" onOpen={openLegal} /><p className="text-xs text-zinc-500">선택 동의를 거부해도 가입할 수 있으며 Settings에서 철회할 수 있습니다.</p></section>
    {error && <p role="alert" className="rounded-lg bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<button disabled={saving || !terms || !privacy} className="h-12 w-full rounded-xl bg-brand-neon font-bold text-black disabled:opacity-50">{saving ? "저장 중..." : "프로필 완성하기"}</button>{legalKey && <LegalModal documentKey={legalKey} onClose={() => setLegalKey(null)} returnFocus={legalTrigger} />}
  </form>;
}

function Consent({ checked, onChange, label, documentKey, onOpen, required = false }: ConsentProps) { return <div className="flex min-h-11 items-center gap-3 rounded-xl border border-white/10 px-4"><input type="checkbox" checked={checked} required={required} onChange={(event) => onChange(event.target.checked)} /><span className="flex-1 text-sm text-zinc-200">{label}</span><button type="button" aria-label={`${label.replace(/ 동의(?: \(.+\))?$/, "")} 전문 보기`} onClick={(event) => onOpen(documentKey, event.currentTarget)} className="text-xs text-zinc-400 underline">전문</button></div>; }
